version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: project-x-db
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_
    volumes: 
      - ./data/data/db
      - ./data/log:/var/log/mongodb
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root_
      ME_CONFIG_MONGODB_URL: mongodb://127.0.0.1:27017/project-x-db
